//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMLB.Tools.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public Nullable<double> player_id { get; set; }
        public Nullable<double> team_id { get; set; }
        public Nullable<double> league_id { get; set; }
        public Nullable<double> position { get; set; }
        public Nullable<double> role { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string nick_name { get; set; }
        public Nullable<double> age { get; set; }
        public string date_of_birth { get; set; }
        public Nullable<double> city_of_birth_id { get; set; }
        public Nullable<double> nation_id { get; set; }
        public Nullable<double> second_nation_id { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> retired { get; set; }
        public Nullable<double> free_agent { get; set; }
        public Nullable<double> last_league_id { get; set; }
        public Nullable<double> last_team_id { get; set; }
        public Nullable<double> organization_id { get; set; }
        public Nullable<double> last_organization_id { get; set; }
        public Nullable<double> language_ids0 { get; set; }
        public Nullable<double> language_ids1 { get; set; }
        public Nullable<double> uniform_number { get; set; }
        public Nullable<double> experience { get; set; }
        public Nullable<double> person_type { get; set; }
        public Nullable<double> bats { get; set; }
        public Nullable<double> throws { get; set; }
        public Nullable<double> personality_greed { get; set; }
        public Nullable<double> personality_loyalty { get; set; }
        public Nullable<double> personality_play_for_winner { get; set; }
        public Nullable<double> personality_work_ethic { get; set; }
        public Nullable<double> personality_intelligence { get; set; }
        public Nullable<double> personality_leader { get; set; }
        public string historical_id { get; set; }
        public string historical_team_id { get; set; }
        public Nullable<double> best_contract_offer_id { get; set; }
        public Nullable<double> injury_is_injured { get; set; }
        public Nullable<double> injury_dtd_injury { get; set; }
        public Nullable<double> injury_career_ending { get; set; }
        public Nullable<double> injury_dl_left { get; set; }
        public Nullable<double> injury_dl_playoff_round { get; set; }
        public Nullable<double> injury_left { get; set; }
        public Nullable<double> dtd_injury_effect { get; set; }
        public Nullable<double> injury_id { get; set; }
        public Nullable<double> prone_overall { get; set; }
        public Nullable<double> prone_leg { get; set; }
        public Nullable<double> prone_back { get; set; }
        public Nullable<double> prone_arm { get; set; }
        public Nullable<double> fatigue_pitches0 { get; set; }
        public Nullable<double> fatigue_pitches1 { get; set; }
        public Nullable<double> fatigue_pitches2 { get; set; }
        public Nullable<double> fatigue_pitches3 { get; set; }
        public Nullable<double> fatigue_pitches4 { get; set; }
        public Nullable<double> fatigue_pitches5 { get; set; }
        public Nullable<double> fatigue_points { get; set; }
        public Nullable<double> fatigue_played_today { get; set; }
        public Nullable<double> running_ratings_speed { get; set; }
        public Nullable<double> running_ratings_stealing { get; set; }
        public Nullable<double> running_ratings_baserunning { get; set; }
        public Nullable<double> college { get; set; }
        public Nullable<double> draft_year { get; set; }
        public Nullable<double> draft_round { get; set; }
        public Nullable<double> draft_supplemental { get; set; }
        public Nullable<double> draft_pick { get; set; }
        public Nullable<double> draft_overall_pick { get; set; }
        public Nullable<double> draft_eligible { get; set; }
        public Nullable<double> hsc_status { get; set; }
        public Nullable<double> picked_in_draft { get; set; }
        public Nullable<double> school { get; set; }
        public Nullable<double> commit_school { get; set; }
        public Nullable<double> hidden { get; set; }
        public Nullable<double> draft_league_id { get; set; }
        public Nullable<double> draft_team_id { get; set; }
        public Nullable<double> turned_coach { get; set; }
        public Nullable<double> hall_of_fame { get; set; }
        public Nullable<double> rust { get; set; }
        public Nullable<double> inducted { get; set; }
        public Nullable<double> strategy_override_team { get; set; }
        public Nullable<double> strategy_stealing { get; set; }
        public Nullable<double> strategy_running { get; set; }
        public Nullable<double> strategy_bunt_for_hit { get; set; }
        public Nullable<double> strategy_sac_bunt { get; set; }
        public Nullable<double> strategy_hit_run { get; set; }
        public Nullable<double> strategy_hook_start { get; set; }
        public Nullable<double> strategy_hook_relief { get; set; }
        public Nullable<double> strategy_pitch_count { get; set; }
        public Nullable<double> strategy_pitch_around { get; set; }
        public Nullable<double> strategy_no_pinch_if_rested { get; set; }
        public Nullable<double> strategy_never_pinch_hit { get; set; }
        public string strategy_defensive_sub { get; set; }
        public Nullable<double> strategy_dtd_sit_min { get; set; }
        public Nullable<double> strategy_dtd_allow_ph { get; set; }
        public Nullable<double> local_pop { get; set; }
        public Nullable<double> national_pop { get; set; }
        public Nullable<double> draft_protected { get; set; }
        public Nullable<double> morale { get; set; }
        public Nullable<double> morale_player_performance { get; set; }
        public Nullable<double> morale_team_performance { get; set; }
        public Nullable<double> morale_team_transactions { get; set; }
        public Nullable<double> expectation { get; set; }
        public Nullable<double> morale_player_role { get; set; }
        public int ID { get; set; }
    }
}
