//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMLB.Tools.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public Nullable<double> team_id { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public string nickname { get; set; }
        public string logo_file_name { get; set; }
        public Nullable<double> city_id { get; set; }
        public Nullable<double> park_id { get; set; }
        public Nullable<double> league_id { get; set; }
        public Nullable<double> sub_league_id { get; set; }
        public Nullable<double> division_id { get; set; }
        public Nullable<double> nation_id { get; set; }
        public Nullable<double> parent_team_id { get; set; }
        public Nullable<double> level { get; set; }
        public Nullable<double> prevent_any_moves { get; set; }
        public Nullable<double> human_team { get; set; }
        public Nullable<double> human_id { get; set; }
        public Nullable<double> gender { get; set; }
        public string background_color_id { get; set; }
        public string text_color_id { get; set; }
        public string ballcaps_main_color_id { get; set; }
        public string ballcaps_visor_color_id { get; set; }
        public string jersey_main_color_id { get; set; }
        public string jersey_away_color_id { get; set; }
        public string jersey_secondary_color_id { get; set; }
        public string jersey_pin_stripes_color_id { get; set; }
        public Nullable<double> allstar_team { get; set; }
        public string historical_id { get; set; }
        public int ID { get; set; }
    }
}
