//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMLB.Tools.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trade_history
    {
        public Nullable<System.DateTime> date { get; set; }
        public string summary { get; set; }
        public Nullable<double> message_id { get; set; }
        public Nullable<double> team_id_0 { get; set; }
        public Nullable<double> player_id_0_0 { get; set; }
        public Nullable<double> draft_round_0_0 { get; set; }
        public Nullable<double> draft_team_0_0 { get; set; }
        public Nullable<double> player_id_0_1 { get; set; }
        public Nullable<double> draft_round_0_1 { get; set; }
        public Nullable<double> draft_team_0_1 { get; set; }
        public Nullable<double> player_id_0_2 { get; set; }
        public Nullable<double> draft_round_0_2 { get; set; }
        public Nullable<double> draft_team_0_2 { get; set; }
        public Nullable<double> player_id_0_3 { get; set; }
        public Nullable<double> draft_round_0_3 { get; set; }
        public Nullable<double> draft_team_0_3 { get; set; }
        public Nullable<double> player_id_0_4 { get; set; }
        public Nullable<double> draft_round_0_4 { get; set; }
        public Nullable<double> draft_team_0_4 { get; set; }
        public Nullable<double> cash_0 { get; set; }
        public Nullable<double> team_id_1 { get; set; }
        public Nullable<double> player_id_1_0 { get; set; }
        public Nullable<double> draft_round_1_0 { get; set; }
        public Nullable<double> draft_team_1_0 { get; set; }
        public Nullable<double> player_id_1_1 { get; set; }
        public Nullable<double> draft_round_1_1 { get; set; }
        public Nullable<double> draft_team_1_1 { get; set; }
        public Nullable<double> player_id_1_2 { get; set; }
        public Nullable<double> draft_round_1_2 { get; set; }
        public Nullable<double> draft_team_1_2 { get; set; }
        public Nullable<double> player_id_1_3 { get; set; }
        public Nullable<double> draft_round_1_3 { get; set; }
        public Nullable<double> draft_team_1_3 { get; set; }
        public Nullable<double> player_id_1_4 { get; set; }
        public Nullable<double> draft_round_1_4 { get; set; }
        public Nullable<double> draft_team_1_4 { get; set; }
        public Nullable<double> cash_1 { get; set; }
        public int ID { get; set; }
    }
}
